config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  post "/insert_round" => "rounds#create"

  devise_for :users

  resources :attempts
  resources :rounds
  resources :plans
  resources :subjects
  resources :exercises

  # Eventually move routes for our React app here
  namespace :api do
    resources :rounds, only: %i[create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/home/_home_student.html.erb
<%= javascript_pack_tag 'student_home' %>

<div id="react-app"></div>
<div class="container d-none" >
  <div class="row" >
    <div class="col-md-12 text-center fw-bold prompt1" >

      Ready to play? Remember, go as FAST as you can!!!
   
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-center">
    <%= form_with(url: rounds_path) do |form| %>
    <%= form.label "How many exercises?" %>
    <%= form.text_field "query_round_length" %>
    <%= form.button "Go", class: "btn btn-dark" %>
    <% end %>
    <div>
  </div>
</div>

app/views/home/_home_tutor.html.erb
<div class="text-center">
  <h1>My Students' Activity</h1>
</div>

<div>
  <%= column_chart @plans.map { |plan|
  { name: plan.student_email, data: (User.find_by(email: plan.student_email)&.attempts&.group_by_day(:created_at)&.count) || {} }
}, ytitle: "Exercises" %>
</div>

<br>
<br>
<br>

<div class="text-center">
  <h1>My Students' Plans</h1>
</div>

<div class="col-md-12">
  <table class="col-md-12">
    <thead>
      <tr>
        <th>Student Email</th>
        <th>Subject</th>
        <th>Questions Per Round</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @plans.each do |plan| %>
        <tr>
          <td><%= plan.student_email %></td>
          <td><%= plan.subject.name %></td>
          <td><%= plan.round_size %></td>
          <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
          <td><%= link_to 'Delete', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<div class="row justify-content-center align-items-center">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header  text-white">
        <h3 class="card-title text-center">Add New Plan</h3>
      </div>
      <div class="card-body">
        <%= form_with(url: plans_path) do |form| %>
          <div class="form-group mb-3">
            <%= label_tag :query_student_email, "Your Student's Email:" %>
            <%= email_field_tag :query_student_email, nil, class: "form-control" %>
          </div>

          <div class="form-group mb-3">
            <%= label_tag :query_subject_id, "Subject:" %>
            <%= select_tag :query_subject_id, options_for_select(Subject.all.map{ |s| [s.name, s.id] }), class: "form-control" %>
          </div>

          <div class="form-group mb-3">
            <%= label_tag :query_round_size, "Round Size (Questions Per Round):" %>
            <%= text_field_tag :query_round_size, nil, class: "form-control" %>
          </div>

          <div class="form-group text-center">
            <%= button_tag "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/home.html.erb
<!DOCTYPE html>
<html>
<head>

</head>

<body>

<% if current_user.tutor? %>
  <%= render "home/home_tutor" %>
<% elsif current_user.student? %>
  <%= render "home/home_student" %>
<% end %> 

<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

</body>