config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  post "/insert_round" => "rounds#create"

  devise_for :users

  resources :attempts
  resources :rounds
  resources :plans
  resources :subjects
  resources :exercises

  # Eventually move routes for our React app here
  namespace :api do
    resources :rounds, only: %i[create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attempt.rb
# == Schema Information
#
# Table name: attempts
#
#  id          :bigint           not null, primary key
#  correct     :boolean
#  finished_at :datetime
#  started_at  :datetime
#  submission  :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  exercise_id :bigint           not null
#  round_id    :bigint           not null
#  student_id  :bigint           not null
#
# Indexes
#
#  index_attempts_on_exercise_id  (exercise_id)
#  index_attempts_on_round_id     (round_id)
#  index_attempts_on_student_id   (student_id)
#
# Foreign Keys
#
#  fk_rails_...  (exercise_id => exercises.id)
#  fk_rails_...  (round_id => rounds.id)
#  fk_rails_...  (student_id => users.id)
#
class Attempt < ApplicationRecord
  belongs_to :exercise
  belongs_to :round
  belongs_to :student, class_name: "User"
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_action :set_attempt, only: %i[ show edit update destroy ]
  skip_forgery_protection

  # GET /attempts or /attempts.json
  def index
    @attempts = Attempt.all
  end

  # GET /attempts/1 or /attempts/1.json
  def show
  end

  # GET /attempts/new
  def new
    @attempt = Attempt.new
  end

  # GET /attempts/1/edit
  def edit
  end

  # POST /attempts or /attempts.json
  def create
    @attempt = Attempt.new

    @attempt.started_at = cookies.fetch(:attempt_started_at)
    @attempt.finished_at = DateTime.now.change(:offset => "+500")
    @attempt.submission = params.fetch("query_submission")

    @attempt.student_id = current_user.id
    @attempt.exercise_id = params.fetch("query_exercise_id")
    @attempt.round_id = params.fetch("query_round_id")
    @attempt.correct = (if @attempt.submission == @attempt.exercise.answer.to_f then true else false end)
    
    attempts_left = cookies.fetch(:attempts_left).to_i
    attempts_left -= 1
    cookies[:attempts_left] = attempts_left
    
    plan = Plan.find_by(student_email: current_user.email)
    @assigned_subject_id = plan.subject_id if plan

    # Adjusting user level here so that exercises are served at the right difficulty
    current_user_level = cookies.fetch(:user_level).to_i
    current_streak = cookies.fetch(:streak_counter).to_i

    if @attempt.correct 
      if (current_user_level != Exercise.where( subject_id: @assigned_subject_id ).maximum(:difficulty)) and (current_streak == 2)
        current_user_level += 1
        cookies[:user_level] = current_user_level
      else
        current_streak += 1
        cookies[:streak_counter] = current_streak
      end
    else
      if current_user_level != 0
        current_user_level = current_user_level - 1
        cookies[:streak_counter] = 0
        cookies[:user_level] = current_user_level
      end
    end

    cookies[:attempt_started_at] = DateTime.now.change(:offset => "+500")

    respond_to do |format|
      if @attempt.save
        if (attempts_left != 0)
          if plan
            format.html { redirect_to exercise_path(Exercise.where( :difficulty => cookies.fetch(:user_level), subject_id: @assigned_subject_id ).shuffle.first.id), notice: "Attempt recorded!" }
            exercise = Exercise.where( :difficulty => cookies.fetch(:user_level), subject_id: @assigned_subject_id ).shuffle.first
          else
            format.html { redirect_to exercise_path(Exercise.where( :difficulty => cookies.fetch(:user_level)).shuffle.first.id), notice: "Attempt recorded!" }
            exercise = Exercise.where( :difficulty => cookies.fetch(:user_level)).shuffle.first
          end

          format.json {render json: exercise}
        elsif (attempts_left == 0)
          format.html { redirect_to round_path(cookies.fetch(:current_round)), notice: "Attempt recorded and round complete!" }
          format.json { render :show, status: :created, location: @attempt }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attempt.errors, status: :unprocessable_entity }
      end
    end



    
  end

  # PATCH/PUT /attempts/1 or /attempts/1.json
  def update
    respond_to do |format|
      if @attempt.update(attempt_params)
        format.html { redirect_to attempt_url(@attempt), notice: "Attempt was successfully updated." }
        format.json { render :show, status: :ok, location: @attempt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attempts/1 or /attempts/1.json
  def destroy
    @attempt.destroy

    respond_to do |format|
      format.html { redirect_to attempts_url, notice: "Attempt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attempt
      @attempt = Attempt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attempt_params
      params.require(:attempt).permit(:submission, :correct, :started_at, :finished_at, :exercise_id, :round_id, :student_id)
    end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/views/attempts/_form.html.erb
<%= form_with(model: attempt) do |form| %>
  <% if attempt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attempt.errors.count, "error") %> prohibited this attempt from being saved:</h2>

      <ul>
        <% attempt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :submission %>
    <%= form.text_field :submission %>
  </div>

  <div class="field">
    <%= form.label :correct %>
    <%= form.check_box :correct %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at %>
  </div>

  <div class="field">
    <%= form.label :finished_at %>
    <%= form.datetime_select :finished_at %>
  </div>

  <div class="field">
    <%= form.label :exercise_id %>
    <%= form.text_field :exercise_id %>
  </div>

  <div class="field">
    <%= form.label :round_id %>
    <%= form.text_field :round_id %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attempts/edit.html.erb
<h1>Editing Attempt</h1>

<%= render 'form', attempt: @attempt %>

<%= link_to 'Show', @attempt %> |
<%= link_to 'Back', attempts_path %>

app/views/attempts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attempts</h1>

<table>
  <thead>
    <tr>
      <th>Submission</th>
      <th>Correct</th>
      <th>Started at</th>
      <th>Finished at</th>
      <th>Exercise</th>
      <th>Round</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attempts.each do |attempt| %>
      <tr>
        <td><%= attempt.submission %></td>
        <td><%= attempt.correct %></td>
        <td><%= attempt.started_at %></td>
        <td><%= attempt.finished_at %></td>
        <td><%= attempt.exercise_id %></td>
        <td><%= attempt.round_id %></td>
        <td><%= attempt.student_id %></td>
        <td><%= link_to 'Show', attempt %></td>
        <td><%= link_to 'Edit', edit_attempt_path(attempt) %></td>
        <td><%= link_to 'Destroy', attempt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attempt', new_attempt_path %>

app/views/attempts/new.html.erb
<h1>New Attempt</h1>

<%= render 'form', attempt: @attempt %>

<%= link_to 'Back', attempts_path %>

app/views/attempts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Submission:</strong>
  <%= @attempt.submission %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @attempt.correct %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @attempt.started_at %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @attempt.finished_at %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= @attempt.exercise_id %>
</p>

<p>
  <strong>Round:</strong>
  <%= @attempt.round_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @attempt.student_id %>
</p>

<%= link_to 'Edit', edit_attempt_path(@attempt) %> |
<%= link_to 'Back', attempts_path %>