config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  post "/insert_round" => "rounds#create"

  devise_for :users

  resources :attempts
  resources :rounds
  resources :plans
  resources :subjects
  resources :exercises

  # Eventually move routes for our React app here
  namespace :api do
    resources :rounds, only: %i[create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
# == Schema Information
#
# Table name: plans
#
#  id            :bigint           not null, primary key
#  round_size    :integer
#  student_email :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  student_id    :bigint
#  subject_id    :bigint           not null
#  tutor_id      :bigint           not null
#
# Indexes
#
#  index_plans_on_student_id  (student_id)
#  index_plans_on_subject_id  (subject_id)
#  index_plans_on_tutor_id    (tutor_id)
#
# Foreign Keys
#
#  fk_rails_...  (student_id => users.id)
#  fk_rails_...  (subject_id => subjects.id)
#  fk_rails_...  (tutor_id => users.id)
#
class Plan < ApplicationRecord
  belongs_to :tutor, class_name: "User"
  belongs_to :student, class_name: "User", optional: true
  belongs_to :subject
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]
  before_action :require_user_be_tutor

  # GET /plans or /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1 or /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new
    @plan.tutor_id = current_user.id

    # find the student by email
    student = User.find_by(email: params.fetch("query_student_email"))
    @plan.student_id = student&.id
    @plan.student_email = params.fetch("query_student_email")

    @plan.subject_id = params.fetch("query_subject_id")
    @plan.round_size = params.fetch("query_round_size")

    respond_to do |format|
      if @plan.save
        flash[:notice] = "Plan was successfully created."
        @plans = Plan.where(tutor_id: current_user.id)
        format.html { render "home/home" }
        format.json { render :show, status: :created, location: @plan }
      else
        @plans = Plan.where(tutor_id: current_user.id)
        flash.now[:alert] = "Plan could not be created."
        flash.now[:error_messages] = @plan.errors.full_messages
        format.html { render 'home/home', status: :unprocessable_entity } # Replace 'controller_name' with the actual controller name.
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to root_path, notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:tutor_id, :student_id, :subject_id, :round_size)
    end

    def require_user_be_tutor
      unless current_user.tutor?
        redirect_back fallback_location: root_path
      end
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>
      <ul>
        <% plan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :student_email, "Your Student's Email:" %>
    <%= form.email_field :student_email, value: plan.student_email, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :subject_id, "Subject:" %>
    <%= form.select :subject_id, options_for_select(Subject.all.map{ |s| [s.name, s.id] }, plan.subject_id), {}, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :round_size, "Round Size (Questions Per Round):" %>
    <%= form.text_field :round_size, class: "form-control" %>
  </div>

  <div class="form-group text-center">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/plans/edit.html.erb
<div class="row justify-content-center align-items-center">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header text-white">
        <h3 class="card-title text-center">Editing Plan</h3>
      </div>
      <div class="card-body form-group mb-3">
        <%= render 'form', plan: @plan %>
      </div>
      <div class="card-footer">
        <div class="d-flex justify-content-between">
          <%= link_to 'Back', root_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Tutor</th>
      <th>Student</th>
      <th>Subject</th>
      <th>Round size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.tutor_id %></td>
        <td><%= plan.student_id %></td>
        <td><%= plan.subject_id %></td>
        <td><%= plan.round_size %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_with(url: plans_path) do |form| %>
  <div class="form-outline prompt2">
    <%= label_tag :submit_student, "Your Student's ID:"%>
    <%= text_field_tag :query_student_id %>    
    <br>
    <%= label_tag :submit_subject, "Subject ID:"%>
    <%= text_field_tag :query_subject_id %>  
    <br>
    <%= label_tag :submit_round_size, "Round Size:"%>  
    <%= text_field_tag :query_round_size %>    
    <br>
  <%= button_tag "Submit", class: "btn btn-dark" %>

  </div>
<% end %>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tutor:</strong>
  <%= @plan.tutor_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @plan.student_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @plan.subject_id %>
</p>

<p>
  <strong>Round size:</strong>
  <%= @plan.round_size %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>